all:
	javac DistanceVector.java
	javac PoisonedReverse.java
	javac InputHandler.java
	javac Output_transformer.java
	javac RouterConfig.java
	javac Router.java
	
	
clean:
	rm DistanceVector PoisonedReverse InputHandler Output_transformer RouterConfig Router